"use client";

import { useState } from "react";
import SEO from "@/components/SEO";
import { formatNumber, percentageChange, percentageOf, percentOf, valueAfterPercentage } from "@/lib/final-tools-1";
import { useTranslations } from "next-intl";

function NumberInput({ value, onChange, placeholder }: { value: string; onChange: (value: string) => void; placeholder: string }) { return <input type="number" value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} className="w-full rounded-lg border border-[#E0E0E0] bg-white px-3 py-2 text-[#2D4D35]" />; }
function Card({ title, children }: { title: string; children: React.ReactNode }) { return <section className="glass-card-dark rounded-[24px] p-6"><h2 className="mb-4 text-lg font-bold text-[#2D4D35]">{title}</h2>{children}</section>; }
export default function PercentageCalculator() {
  const t = useTranslations("Tools.PercentageCalculator");
  const [x, setX] = useState(""); const [y, setY] = useState(""); const [from, setFrom] = useState(""); const [to, setTo] = useState(""); const [base, setBase] = useState(""); const [rate, setRate] = useState(""); const [increase, setIncrease] = useState(true);
  const pair = (fn: (a: number, b: number) => number | null, a: string, b: string) => a !== "" && b !== "" ? formatNumber(fn(Number(a), Number(b))) : "";
  return <main className="min-h-screen px-6 pb-20 pt-32 text-foreground"><SEO title={t("title")} description={t("description")} keywords="percentage calculator percent change" /><div className="mx-auto max-w-4xl"><header className="mb-10 text-center"><h1 className="gradient-text text-4xl font-bold lg:text-5xl">{t("title")}</h1><p className="mt-3 text-[#4A6857]">{t("description")}</p></header><div className="grid gap-5 md:grid-cols-2"><Card title={t("whatIs")}><div className="grid grid-cols-[1fr_auto_1fr_auto] items-center gap-2"><NumberInput value={x} onChange={setX} placeholder="X" /><span>%</span><NumberInput value={y} onChange={setY} placeholder="Y" /><output className="rounded-lg bg-white px-3 py-2 font-semibold">{pair(percentageOf, x, y)}</output></div></Card><Card title={t("whatPercent")}><div className="grid grid-cols-[1fr_auto_1fr_auto] items-center gap-2"><NumberInput value={x} onChange={setX} placeholder="X" /><span>/</span><NumberInput value={y} onChange={setY} placeholder="Y" /><output className="rounded-lg bg-white px-3 py-2 font-semibold">{pair(percentOf, x, y)}%</output></div></Card><Card title={t("change")}><div className="grid grid-cols-[1fr_auto_1fr_auto] items-center gap-2"><NumberInput value={from} onChange={setFrom} placeholder={t("from")} /><span>→</span><NumberInput value={to} onChange={setTo} placeholder={t("to")} /><output className="rounded-lg bg-white px-3 py-2 font-semibold">{pair(percentageChange, from, to)}%</output></div></Card><Card title={t("afterChange")}><div className="grid gap-3 sm:grid-cols-2"><NumberInput value={base} onChange={setBase} placeholder={t("value")} /><NumberInput value={rate} onChange={setRate} placeholder="%" /></div><div className="mt-3 flex items-center gap-4 text-sm text-[#2D4D35]"><label><input type="radio" checked={increase} onChange={() => setIncrease(true)} /> {t("increase")}</label><label><input type="radio" checked={!increase} onChange={() => setIncrease(false)} /> {t("decrease")}</label></div><output className="mt-4 block rounded-lg bg-white px-3 py-2 font-semibold text-[#2D4D35]">{base !== "" && rate !== "" ? formatNumber(valueAfterPercentage(Number(base), Number(rate), increase)) : ""}</output></Card></div></div></main>;
}
