"use client";

import { useMemo, useState } from "react";
import SEO from "@/components/SEO";
import { convertTemperature, type TemperatureUnit } from "@/lib/math-media-1";
import { useTranslations } from "next-intl";

const units: TemperatureUnit[] = ["C", "F", "K", "R", "De"];
export default function TemperatureConverter() { const t = useTranslations("Tools.TemperatureConverter"); const [value, setValue] = useState("20"); const [from, setFrom] = useState<TemperatureUnit>("C"); const [precision, setPrecision] = useState("2"); const converted = useMemo(() => { const number = Number(value); if (!Number.isFinite(number)) return null; return units.reduce<Record<string, string>>((all, unit) => { all[unit] = convertTemperature(number, from, unit).toFixed(Number(precision)); return all; }, {}); }, [from, precision, value]); return <main className="min-h-screen px-6 pb-20 pt-32 text-foreground"><SEO title={t("title")} description={t("description")} keywords="temperature Celsius Fahrenheit Kelvin Rankine Delisle" /><div className="mx-auto max-w-4xl"><header className="mb-10 text-center"><h1 className="gradient-text text-4xl font-bold lg:text-5xl">{t("title")}</h1><p className="mt-3 text-[#4A6857]">{t("description")}</p></header><section className="glass-card-dark rounded-[24px] p-8"><div className="grid gap-4 sm:grid-cols-3"><label className="text-sm font-semibold text-[#2D4D35]">{t("value")}<input value={value} onChange={(event) => setValue(event.target.value)} type="number" className="mt-2 w-full rounded-xl border border-[#E0E0E0] bg-white px-4 py-3 font-normal" /></label><label className="text-sm font-semibold text-[#2D4D35]">{t("from")}<select value={from} onChange={(event) => setFrom(event.target.value as TemperatureUnit)} className="mt-2 w-full rounded-xl border border-[#E0E0E0] bg-white px-4 py-3 font-normal">{units.map((unit) => <option key={unit}>{unit}</option>)}</select></label><label className="text-sm font-semibold text-[#2D4D35]">{t("precision")}<select value={precision} onChange={(event) => setPrecision(event.target.value)} className="mt-2 w-full rounded-xl border border-[#E0E0E0] bg-white px-4 py-3 font-normal">{[0, 1, 2, 3, 4, 6].map((item) => <option key={item}>{item}</option>)}</select></label></div><div className="mt-7 grid gap-3 sm:grid-cols-2">{units.map((unit) => <div key={unit} className="rounded-xl bg-[#F4F7F4] p-4"><span className="text-sm text-[#4A6857]">{t(unit)}</span><p className="mt-1 font-mono text-xl font-bold text-[#2D4D35]">{converted ? converted[unit] : "—"}°{unit}</p></div>)}</div></section></div></main>; }
