"use client";

import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import SEO from "@/components/SEO";
import { BookOpen, HelpCircle, FileText, CheckCircle } from "lucide-react";
import { useTranslations } from "next-intl";

export default function Terms() {
  const t = useTranslations("Legal.terms");
  return (
    <div className="min-h-screen bg-transparent text-foreground">
      <SEO
        title="Terms & Conditions"
        description="Learn about our digital user guidelines, server safety, and compliance clauses."
        keywords="terms, conditions, rules, agreement, licensing"
      />

      <main className="pt-32 pb-20 px-6">
        <div className="max-w-[800px] mx-auto space-y-8">
          {/* Header */}
          <div className="border-b border-[#C5DCC9] pb-6">
            <h1 className="text-3xl lg:text-4xl font-bold leading-tight text-[#1F3A26] mb-2">
              {t("title")}
            </h1>
            <p className="text-sm text-[#4A6857]">
              {t("effective")}
            </p>
          </div>

          {/* Quick info grid */}
          <div className="grid sm:grid-cols-2 gap-4">
            <div className="p-4 rounded-xl border border-[#C5DCC9] bg-[#F0F7F0] flex items-center gap-3">
              <CheckCircle className="w-5 h-5 text-[#10A968] shrink-0" />
              <span className="text-xs text-[#2D4D35]">Fully free for general use</span>
            </div>
            <div className="p-4 rounded-xl border border-[#C5DCC9] bg-[#F0F7F0] flex items-center gap-3">
              <CheckCircle className="w-5 h-5 text-[#10A968] shrink-0" />
              <span className="text-xs text-[#2D4D35]">Commercial and print permissions</span>
            </div>
          </div>

          {/* Terms sections */}
          <div className="space-y-6 text-[#4A6857] leading-relaxed text-sm">
            <section className="space-y-3">
              <h2 className="text-lg font-bold text-[#1F3A26]">1. Contract Acceptance</h2>
              <p>
                By opening, viewing, or interacting with the TechTools web application, you agree to comply with and be bound by these legal Terms and Conditions of service. If you do not agree to these terms, please stop using our digital platform immediately.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-lg font-bold text-[#1F3A26]">2. Software & Tool License</h2>
              <p>
                We grant you a non-exclusive, non-transferable, revocable license to use our utilities (Color Picker, Internet Speed Test, QR Generator, and Typing Test) for personal, educational, or professional work. High-resolution printouts, downloaded images, and exported code blocks generated by our software are entirely yours to keep, share, and commercialize.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-lg font-bold text-[#1F3A26]">3. Acceptable Use Policy</h2>
              <p>
                You agree not to attempt to reverse engineer our code patterns, distribute massive bot payloads designed to interfere with our email forms, or wrap our pages inside hidden frames for fraudulent uses.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-lg font-bold text-[#1F3A26]">4. Disclaimer of Warranty</h2>
              <p>
                ALL SERVICES AND CALCULATORS ARE PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT ANY EXPRESS OR IMPLIED WARRANTY, INCLUDING BUT NOT LIMITED TO TIMELINESS, PERFORMANCE STABILITY, OR COMPREHENSIVE ACCURACY. IN NO EVENT SHALL TECHTOOLS BE LIABLE FOR ANY CONSEQUENTIAL DATA LOSS, CONNECTION TERMINATION, OR ACCIDENT DURING USE.
              </p>
            </section>
          </div>
        </div>
      </main>
    </div>
  );
}
