"use client";
import { useCallback, useEffect, useState } from "react";
import SEO from "@/components/SEO";
import { generateUuid, type UuidVersion } from "@/lib/crypto-tools";
import { useTranslations } from "next-intl";

const versions: UuidVersion[] = ["NIL", "v1", "v3", "v4", "v5"];
const namespaces = { DNS: "6ba7b810-9dad-11d1-80b4-00c04fd430c8", URL: "6ba7b811-9dad-11d1-80b4-00c04fd430c8", OID: "6ba7b812-9dad-11d1-80b4-00c04fd430c8", X500: "6ba7b814-9dad-11d1-80b4-00c04fd430c8" };
export default function UuidGenerator() {
  const t = useTranslations("Tools.UuidGenerator");
  const [version, setVersion] = useState<UuidVersion>("v4"); const [count, setCount] = useState(1); const [namespace, setNamespace] = useState(namespaces.URL); const [name, setName] = useState(""); const [uuids, setUuids] = useState(""); const [copied, setCopied] = useState(false);
  const refresh = useCallback(async () => { setUuids((await Promise.all(Array.from({ length: count }, (_, i) => generateUuid(version, name, namespace, i)))).join("\n")); }, [count, name, namespace, version]);
  useEffect(() => { void refresh(); }, [refresh]);
  const copy = async () => { await navigator.clipboard.writeText(uuids); setCopied(true); setTimeout(() => setCopied(false), 1500); };
  return <main className="min-h-screen px-6 pt-32 pb-20 text-foreground"><SEO title={t("title")} description={t("description")} keywords="UUID generator, UUID v4, UUID v5" /><div className="mx-auto max-w-3xl"><header className="mb-10 text-center"><h1 className="gradient-text text-4xl font-bold">{t("title")}</h1><p className="mt-3 text-[#4A6857]">{t("description")}</p></header><section className="glass-card-dark space-y-5 rounded-[24px] p-8"><label className="block text-sm font-semibold text-[#2D4D35]">{t("version")}<select value={version} onChange={e => setVersion(e.target.value as UuidVersion)} className="mt-2 w-full rounded-lg border border-[#E0E0E0] bg-white px-3 py-2 text-[#2D4D35]">{versions.map(v => <option key={v}>{v}</option>)}</select></label><label className="block text-sm font-semibold text-[#2D4D35]">{t("quantity")}<input type="number" min={1} max={50} value={count} onChange={e => setCount(Math.max(1, Math.min(50, Number(e.target.value))))} className="mt-2 w-full rounded-lg border border-[#E0E0E0] bg-white px-3 py-2" /></label>{(version === "v3" || version === "v5") && <><label className="block text-sm font-semibold text-[#2D4D35]">{t("namespace")}<select value={namespace} onChange={e => setNamespace(e.target.value)} className="mt-2 w-full rounded-lg border border-[#E0E0E0] bg-white px-3 py-2">{Object.entries(namespaces).map(([key, value]) => <option value={value} key={key}>{key}</option>)}</select></label><label className="block text-sm font-semibold text-[#2D4D35]">{t("name")}<input value={name} onChange={e => setName(e.target.value)} className="mt-2 w-full rounded-lg border border-[#E0E0E0] bg-white px-3 py-2" /></label></>}<textarea value={uuids} readOnly rows={Math.min(count + 1, 12)} className="w-full rounded-xl border border-[#E0E0E0] bg-white p-4 text-center font-mono text-sm text-[#2D4D35]" /><div className="flex justify-center gap-3"><button onClick={copy} className="rounded-xl bg-gradient-indigo-cyan px-5 py-3 font-semibold text-white">{copied ? t("copied") : t("copy")}</button><button onClick={() => void refresh()} className="rounded-xl border border-[#10A968] px-5 py-3 font-semibold text-[#10A968]">{t("refresh")}</button></div></section></div></main>;
}
