export const defaultLocale = 'en' as const;

export const supportedLocales = ["en","de","es","fr","id","it","nl","pt","tr"] as const;
export const defaultLocale = "en" as const;
export type Locale = (typeof supportedLocales)[number];
export const supportedToolNamespaces = ["UpscaleImage","shared","CropImage","BackgroundRemover","Loading","WatermarkImage","ImageConverter","PdfToPowerpoint","PdfToWord","UnlockPdf","QrGenerator","BarcodeGenerator","BarcodeReader","PasswordGenerator","LoremGenerator","Notepad","EmojiPicker","ColorPicker","PdfDashboard","ImageDashboard","SpeedTest","TypingSpeed"] as const;
export type ToolNamespace = (typeof supportedToolNamespaces)[number];
export type MessageNamespace = 'common' | 'meta' | ToolNamespace;

type Messages = Record<string, unknown>;
const mergeMessages = (base: Messages, override: Messages): Messages => {
  const result = { ...base };
  for (const [key, value] of Object.entries(override)) result[key] = value && typeof value === 'object' && !Array.isArray(value) ? mergeMessages((result[key] as Messages) || {}, value as Messages) : value;
  return result;
};

const loaders: Record<Locale, Record<MessageNamespace, () => Promise<{ default: Messages }>>> = {
  en: { common: () => import('./en/common.json'), meta: () => import('./en/meta.json'), UpscaleImage: () => import('./en/tools/UpscaleImage.json'), shared: () => import('./en/tools/shared.json'), CropImage: () => import('./en/tools/CropImage.json'), BackgroundRemover: () => import('./en/tools/BackgroundRemover.json'), Loading: () => import('./en/tools/Loading.json'), WatermarkImage: () => import('./en/tools/WatermarkImage.json'), ImageConverter: () => import('./en/tools/ImageConverter.json'), PdfToPowerpoint: () => import('./en/tools/PdfToPowerpoint.json'), PdfToWord: () => import('./en/tools/PdfToWord.json'), UnlockPdf: () => import('./en/tools/UnlockPdf.json'), QrGenerator: () => import('./en/tools/QrGenerator.json'), BarcodeGenerator: () => import('./en/tools/BarcodeGenerator.json'), BarcodeReader: () => import('./en/tools/BarcodeReader.json'), PasswordGenerator: () => import('./en/tools/PasswordGenerator.json'), LoremGenerator: () => import('./en/tools/LoremGenerator.json'), Notepad: () => import('./en/tools/Notepad.json'), EmojiPicker: () => import('./en/tools/EmojiPicker.json'), ColorPicker: () => import('./en/tools/ColorPicker.json'), PdfDashboard: () => import('./en/tools/PdfDashboard.json'), ImageDashboard: () => import('./en/tools/ImageDashboard.json'), SpeedTest: () => import('./en/tools/SpeedTest.json'), TypingSpeed: () => import('./en/tools/TypingSpeed.json'), },
  de: { common: () => import('./de/common.json'), meta: () => import('./de/meta.json'), UpscaleImage: () => import('./de/tools/UpscaleImage.json'), shared: () => import('./de/tools/shared.json'), CropImage: () => import('./de/tools/CropImage.json'), BackgroundRemover: () => import('./de/tools/BackgroundRemover.json'), Loading: () => import('./de/tools/Loading.json'), WatermarkImage: () => import('./de/tools/WatermarkImage.json'), ImageConverter: () => import('./de/tools/ImageConverter.json'), PdfToPowerpoint: () => import('./de/tools/PdfToPowerpoint.json'), PdfToWord: () => import('./de/tools/PdfToWord.json'), UnlockPdf: () => import('./de/tools/UnlockPdf.json'), QrGenerator: () => import('./de/tools/QrGenerator.json'), BarcodeGenerator: () => import('./de/tools/BarcodeGenerator.json'), BarcodeReader: () => import('./de/tools/BarcodeReader.json'), PasswordGenerator: () => import('./de/tools/PasswordGenerator.json'), LoremGenerator: () => import('./de/tools/LoremGenerator.json'), Notepad: () => import('./de/tools/Notepad.json'), EmojiPicker: () => import('./de/tools/EmojiPicker.json'), ColorPicker: () => import('./de/tools/ColorPicker.json'), PdfDashboard: () => import('./de/tools/PdfDashboard.json'), ImageDashboard: () => import('./de/tools/ImageDashboard.json'), SpeedTest: () => import('./de/tools/SpeedTest.json'), TypingSpeed: () => import('./de/tools/TypingSpeed.json'), },
  es: { common: () => import('./es/common.json'), meta: () => import('./es/meta.json'), UpscaleImage: () => import('./es/tools/UpscaleImage.json'), shared: () => import('./es/tools/shared.json'), CropImage: () => import('./es/tools/CropImage.json'), BackgroundRemover: () => import('./es/tools/BackgroundRemover.json'), Loading: () => import('./es/tools/Loading.json'), WatermarkImage: () => import('./es/tools/WatermarkImage.json'), ImageConverter: () => import('./es/tools/ImageConverter.json'), PdfToPowerpoint: () => import('./es/tools/PdfToPowerpoint.json'), PdfToWord: () => import('./es/tools/PdfToWord.json'), UnlockPdf: () => import('./es/tools/UnlockPdf.json'), QrGenerator: () => import('./es/tools/QrGenerator.json'), BarcodeGenerator: () => import('./es/tools/BarcodeGenerator.json'), BarcodeReader: () => import('./es/tools/BarcodeReader.json'), PasswordGenerator: () => import('./es/tools/PasswordGenerator.json'), LoremGenerator: () => import('./es/tools/LoremGenerator.json'), Notepad: () => import('./es/tools/Notepad.json'), EmojiPicker: () => import('./es/tools/EmojiPicker.json'), ColorPicker: () => import('./es/tools/ColorPicker.json'), PdfDashboard: () => import('./es/tools/PdfDashboard.json'), ImageDashboard: () => import('./es/tools/ImageDashboard.json'), SpeedTest: () => import('./es/tools/SpeedTest.json'), TypingSpeed: () => import('./es/tools/TypingSpeed.json'), },
  fr: { common: () => import('./fr/common.json'), meta: () => import('./fr/meta.json'), UpscaleImage: () => import('./fr/tools/UpscaleImage.json'), shared: () => import('./fr/tools/shared.json'), CropImage: () => import('./fr/tools/CropImage.json'), BackgroundRemover: () => import('./fr/tools/BackgroundRemover.json'), Loading: () => import('./fr/tools/Loading.json'), WatermarkImage: () => import('./fr/tools/WatermarkImage.json'), ImageConverter: () => import('./fr/tools/ImageConverter.json'), PdfToPowerpoint: () => import('./fr/tools/PdfToPowerpoint.json'), PdfToWord: () => import('./fr/tools/PdfToWord.json'), UnlockPdf: () => import('./fr/tools/UnlockPdf.json'), QrGenerator: () => import('./fr/tools/QrGenerator.json'), BarcodeGenerator: () => import('./fr/tools/BarcodeGenerator.json'), BarcodeReader: () => import('./fr/tools/BarcodeReader.json'), PasswordGenerator: () => import('./fr/tools/PasswordGenerator.json'), LoremGenerator: () => import('./fr/tools/LoremGenerator.json'), Notepad: () => import('./fr/tools/Notepad.json'), EmojiPicker: () => import('./fr/tools/EmojiPicker.json'), ColorPicker: () => import('./fr/tools/ColorPicker.json'), PdfDashboard: () => import('./fr/tools/PdfDashboard.json'), ImageDashboard: () => import('./fr/tools/ImageDashboard.json'), SpeedTest: () => import('./fr/tools/SpeedTest.json'), TypingSpeed: () => import('./fr/tools/TypingSpeed.json'), },
  id: { common: () => import('./id/common.json'), meta: () => import('./id/meta.json'), UpscaleImage: () => import('./id/tools/UpscaleImage.json'), shared: () => import('./id/tools/shared.json'), CropImage: () => import('./id/tools/CropImage.json'), BackgroundRemover: () => import('./id/tools/BackgroundRemover.json'), Loading: () => import('./id/tools/Loading.json'), WatermarkImage: () => import('./id/tools/WatermarkImage.json'), ImageConverter: () => import('./id/tools/ImageConverter.json'), PdfToPowerpoint: () => import('./id/tools/PdfToPowerpoint.json'), PdfToWord: () => import('./id/tools/PdfToWord.json'), UnlockPdf: () => import('./id/tools/UnlockPdf.json'), QrGenerator: () => import('./id/tools/QrGenerator.json'), BarcodeGenerator: () => import('./id/tools/BarcodeGenerator.json'), BarcodeReader: () => import('./id/tools/BarcodeReader.json'), PasswordGenerator: () => import('./id/tools/PasswordGenerator.json'), LoremGenerator: () => import('./id/tools/LoremGenerator.json'), Notepad: () => import('./id/tools/Notepad.json'), EmojiPicker: () => import('./id/tools/EmojiPicker.json'), ColorPicker: () => import('./id/tools/ColorPicker.json'), PdfDashboard: () => import('./id/tools/PdfDashboard.json'), ImageDashboard: () => import('./id/tools/ImageDashboard.json'), SpeedTest: () => import('./id/tools/SpeedTest.json'), TypingSpeed: () => import('./id/tools/TypingSpeed.json'), },
  it: { common: () => import('./it/common.json'), meta: () => import('./it/meta.json'), UpscaleImage: () => import('./it/tools/UpscaleImage.json'), shared: () => import('./it/tools/shared.json'), CropImage: () => import('./it/tools/CropImage.json'), BackgroundRemover: () => import('./it/tools/BackgroundRemover.json'), Loading: () => import('./it/tools/Loading.json'), WatermarkImage: () => import('./it/tools/WatermarkImage.json'), ImageConverter: () => import('./it/tools/ImageConverter.json'), PdfToPowerpoint: () => import('./it/tools/PdfToPowerpoint.json'), PdfToWord: () => import('./it/tools/PdfToWord.json'), UnlockPdf: () => import('./it/tools/UnlockPdf.json'), QrGenerator: () => import('./it/tools/QrGenerator.json'), BarcodeGenerator: () => import('./it/tools/BarcodeGenerator.json'), BarcodeReader: () => import('./it/tools/BarcodeReader.json'), PasswordGenerator: () => import('./it/tools/PasswordGenerator.json'), LoremGenerator: () => import('./it/tools/LoremGenerator.json'), Notepad: () => import('./it/tools/Notepad.json'), EmojiPicker: () => import('./it/tools/EmojiPicker.json'), ColorPicker: () => import('./it/tools/ColorPicker.json'), PdfDashboard: () => import('./it/tools/PdfDashboard.json'), ImageDashboard: () => import('./it/tools/ImageDashboard.json'), SpeedTest: () => import('./it/tools/SpeedTest.json'), TypingSpeed: () => import('./it/tools/TypingSpeed.json'), },
  nl: { common: () => import('./nl/common.json'), meta: () => import('./nl/meta.json'), UpscaleImage: () => import('./nl/tools/UpscaleImage.json'), shared: () => import('./nl/tools/shared.json'), CropImage: () => import('./nl/tools/CropImage.json'), BackgroundRemover: () => import('./nl/tools/BackgroundRemover.json'), Loading: () => import('./nl/tools/Loading.json'), WatermarkImage: () => import('./nl/tools/WatermarkImage.json'), ImageConverter: () => import('./nl/tools/ImageConverter.json'), PdfToPowerpoint: () => import('./nl/tools/PdfToPowerpoint.json'), PdfToWord: () => import('./nl/tools/PdfToWord.json'), UnlockPdf: () => import('./nl/tools/UnlockPdf.json'), QrGenerator: () => import('./nl/tools/QrGenerator.json'), BarcodeGenerator: () => import('./nl/tools/BarcodeGenerator.json'), BarcodeReader: () => import('./nl/tools/BarcodeReader.json'), PasswordGenerator: () => import('./nl/tools/PasswordGenerator.json'), LoremGenerator: () => import('./nl/tools/LoremGenerator.json'), Notepad: () => import('./nl/tools/Notepad.json'), EmojiPicker: () => import('./nl/tools/EmojiPicker.json'), ColorPicker: () => import('./nl/tools/ColorPicker.json'), PdfDashboard: () => import('./nl/tools/PdfDashboard.json'), ImageDashboard: () => import('./nl/tools/ImageDashboard.json'), SpeedTest: () => import('./nl/tools/SpeedTest.json'), TypingSpeed: () => import('./nl/tools/TypingSpeed.json'), },
  pt: { common: () => import('./pt/common.json'), meta: () => import('./pt/meta.json'), UpscaleImage: () => import('./pt/tools/UpscaleImage.json'), shared: () => import('./pt/tools/shared.json'), CropImage: () => import('./pt/tools/CropImage.json'), BackgroundRemover: () => import('./pt/tools/BackgroundRemover.json'), Loading: () => import('./pt/tools/Loading.json'), WatermarkImage: () => import('./pt/tools/WatermarkImage.json'), ImageConverter: () => import('./pt/tools/ImageConverter.json'), PdfToPowerpoint: () => import('./pt/tools/PdfToPowerpoint.json'), PdfToWord: () => import('./pt/tools/PdfToWord.json'), UnlockPdf: () => import('./pt/tools/UnlockPdf.json'), QrGenerator: () => import('./pt/tools/QrGenerator.json'), BarcodeGenerator: () => import('./pt/tools/BarcodeGenerator.json'), BarcodeReader: () => import('./pt/tools/BarcodeReader.json'), PasswordGenerator: () => import('./pt/tools/PasswordGenerator.json'), LoremGenerator: () => import('./pt/tools/LoremGenerator.json'), Notepad: () => import('./pt/tools/Notepad.json'), EmojiPicker: () => import('./pt/tools/EmojiPicker.json'), ColorPicker: () => import('./pt/tools/ColorPicker.json'), PdfDashboard: () => import('./pt/tools/PdfDashboard.json'), ImageDashboard: () => import('./pt/tools/ImageDashboard.json'), SpeedTest: () => import('./pt/tools/SpeedTest.json'), TypingSpeed: () => import('./pt/tools/TypingSpeed.json'), },
  tr: { common: () => import('./tr/common.json'), meta: () => import('./tr/meta.json'), UpscaleImage: () => import('./tr/tools/UpscaleImage.json'), shared: () => import('./tr/tools/shared.json'), CropImage: () => import('./tr/tools/CropImage.json'), BackgroundRemover: () => import('./tr/tools/BackgroundRemover.json'), Loading: () => import('./tr/tools/Loading.json'), WatermarkImage: () => import('./tr/tools/WatermarkImage.json'), ImageConverter: () => import('./tr/tools/ImageConverter.json'), PdfToPowerpoint: () => import('./tr/tools/PdfToPowerpoint.json'), PdfToWord: () => import('./tr/tools/PdfToWord.json'), UnlockPdf: () => import('./tr/tools/UnlockPdf.json'), QrGenerator: () => import('./tr/tools/QrGenerator.json'), BarcodeGenerator: () => import('./tr/tools/BarcodeGenerator.json'), BarcodeReader: () => import('./tr/tools/BarcodeReader.json'), PasswordGenerator: () => import('./tr/tools/PasswordGenerator.json'), LoremGenerator: () => import('./tr/tools/LoremGenerator.json'), Notepad: () => import('./tr/tools/Notepad.json'), EmojiPicker: () => import('./tr/tools/EmojiPicker.json'), ColorPicker: () => import('./tr/tools/ColorPicker.json'), PdfDashboard: () => import('./tr/tools/PdfDashboard.json'), ImageDashboard: () => import('./tr/tools/ImageDashboard.json'), SpeedTest: () => import('./tr/tools/SpeedTest.json'), TypingSpeed: () => import('./tr/tools/TypingSpeed.json'), },
};

export async function loadMessages(locale: Locale, namespaces: readonly MessageNamespace[] = ['common', 'meta']): Promise<Messages> {
  const selected = namespaces.length ? namespaces : ['common'];
  const loaded = await Promise.all(selected.map(async (namespace) => [namespace, (await loaders[locale][namespace]()).default] as const));
  const common = loaded.find(([namespace]) => namespace === 'common')?.[1] || {};
  const meta = loaded.find(([namespace]) => namespace === 'meta')?.[1] || {};
  const tools = Object.fromEntries(loaded.filter(([namespace]) => namespace !== 'common' && namespace !== 'meta').map(([namespace, value]) => [namespace, value]));
  return { ...(common as Messages), ...(meta as Messages), ...(Object.keys(tools).length ? { Tools: tools } : {}) };
}

export const publicRoutes = {"home":"/","about":"/about-us","tools":"/tools","blog":"/blog","pricing":"/pricing","help":"/help","contact":"/contact-us","privacy":"/privacy-policy","terms":"/terms-and-conditions","pdf":"/ilovepdf","image":"/iloveimg","qrGenerator":"/qr-generator","barcodeGenerator":"/barcode-generator","barcodeReader":"/barcode-reader","passwordGenerator":"/password-generator","loremGenerator":"/lorem-ipsum-generator","emojiPicker":"/emoji-picker","notepad":"/notepad","colorPicker":"/color-picker","speedTest":"/speed-test","typingSpeed":"/typing-speed"} as const;
