"use client";

/** Metadata is generated by Next.js route layouts. This compatibility component
 * intentionally renders nothing so hydration cannot overwrite canonical,
 * hreflang, Open Graph, or structured-data tags. */
export interface SEOProps {
  title: string; description: string; keywords?: string; categoryName?: string;
  toolName?: string; isDashboard?: boolean; isHome?: boolean; imageUrl?: string;
}
export default function SEO(_props: SEOProps) { return null; }
