const digits = "0123456789abcdefghijklmnopqrstuvwxyz";
export function convertIntegerBase(value: string, fromBase: number, toBase: number) { if (!Number.isInteger(fromBase) || !Number.isInteger(toBase) || fromBase < 2 || toBase < 2 || fromBase > 36 || toBase > 36) throw new Error("Bases must be between 2 and 36"); const raw = value.trim().toLowerCase(); if (!raw) return ""; if (![...raw].every(char => { const index = digits.indexOf(char); return index >= 0 && index < fromBase; })) throw new Error(`Invalid digit for base ${fromBase}`); let decimal = BigInt(0); for (const char of raw) decimal = decimal * BigInt(fromBase) + BigInt(digits.indexOf(char)); if (decimal === 0n) return "0"; let result = ""; while (decimal > 0n) { result = digits[Number(decimal % BigInt(toBase))] + result; decimal /= BigInt(toBase); } return result; }
const romanValues: Array<[string, number]> = [["M", 1000], ["CM", 900], ["D", 500], ["CD", 400], ["C", 100], ["XC", 90], ["L", 50], ["XL", 40], ["X", 10], ["IX", 9], ["V", 5], ["IV", 4], ["I", 1]];
export function arabicToRoman(value: number) { if (!Number.isInteger(value) || value < 1 || value > 3999) return ""; let result = ""; let remainder = value; for (const [roman, number] of romanValues) while (remainder >= number) { result += roman; remainder -= number; } return result; }
export function romanToArabic(value: string) { const roman = value.trim().toUpperCase(); if (!/^(M{0,3}(CM|CD|D?C{0,3})(XC|XL|L?X{0,3})(IX|IV|V?I{0,3}))$/.test(roman) || !roman) return null; let total = 0; for (let i = 0; i < roman.length; i++) { const current = { I: 1, V: 5, X: 10, L: 50, C: 100, D: 500, M: 1000 }[roman[i] as "I"]; const next = { I: 1, V: 5, X: 10, L: 50, C: 100, D: 500, M: 1000 }[roman[i + 1] as "I"] || 0; total += current < next ? -current : current; } return total; }
export function fileToBase64(file: File) { return new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = () => reject(reader.error); reader.readAsDataURL(file); }); }
export function base64Mime(value: string) { return value.match(/^data:([^;,]+)/)?.[1] || "application/octet-stream"; }
export function base64Payload(value: string) { return value.includes(",") ? value.slice(value.indexOf(",") + 1) : value.replace(/\s/g, ""); }
export function binaryToText(value: string, bits = 8) { const clean = value.replace(/[^01]/g, ""); if (!Number.isInteger(bits) || bits < 1 || bits > 16 || clean.length % bits !== 0) throw new Error("Binary must contain complete byte groups"); return clean.match(new RegExp(`.{${bits}}`, "g"))?.map(group => String.fromCodePoint(parseInt(group, 2))).join("") || ""; }
export function textToBinary(value: string, bits = 8, separator = " ") { return [...value].map(char => char.codePointAt(0)!.toString(2).padStart(bits, "0")).join(separator); }
