import type { LucideIcon } from "lucide-react";
import { FileText, Image as ImageIcon, ShieldCheck, ArrowRightLeft, Globe2, Code2, Network, Type, Calculator } from "lucide-react";

export type DashboardTool = { id: string; title: string; description: string; route: string; icon: LucideIcon };
export type DashboardCategory = { slug: string; title: string; titleKey: string; description: string; descriptionKey: string; icon: LucideIcon; badgeCount: number; tools: DashboardTool[] };

const tool = (id: string, title: string, route: string, Icon: LucideIcon, description = "A focused utility for everyday technical work."): DashboardTool => ({ id, title, route, icon: Icon, description });
const Arrow = ArrowRightLeft;

export const DASHBOARD_CATEGORIES: DashboardCategory[] = [
  { slug: "pdf-tools-dashboard", title: "PDF Tools Dashboard", titleKey: "pdf", description: "Manage PDF files from one focused workspace.", descriptionKey: "pdfDescription", icon: FileText, badgeCount: 1, tools: [tool("pdf-tools", "PDF Tools", "/ilovepdf", FileText, "Merge, split, convert, compress, and manage PDF files.")] },
  { slug: "image-tools-dashboard", title: "Image Tools Dashboard", titleKey: "image", description: "Edit, convert, and optimize images in one place.", descriptionKey: "imageDescription", icon: ImageIcon, badgeCount: 1, tools: [tool("image-tools", "Image Tools", "/iloveimg", ImageIcon, "Resize, compress, convert, and optimize images.")] },
  { slug: "crypto-security-dashboard", title: "Crypto & Security Dashboard", titleKey: "cryptoSecurity", description: "Protect, validate, hash, and inspect sensitive data.", descriptionKey: "cryptoSecurityDescription", icon: ShieldCheck, badgeCount: 13, tools: [
    tool("password-generator", "Password Generator", "/password-generator", ShieldCheck), tool("password-strength", "Password Strength Analyser", "/password-strength-analyser", ShieldCheck), tool("jwt-parser", "JWT Parser", "/jwt-parser", ShieldCheck), tool("hash-text", "Hash Text", "/hash-text", ShieldCheck), tool("token-generator", "Token Generator", "/token-generator", ShieldCheck), tool("encryption", "Encryption / Decryption", "/encryption-decryption", ShieldCheck), tool("hmac", "HMAC Generator", "/hmac-generator", ShieldCheck), tool("rsa", "RSA Key Pair Generator", "/rsa-key-pair-generator", ShieldCheck), tool("pdf-signature", "PDF Signature Checker", "/pdf-signature-checker", ShieldCheck), tool("bcrypt", "Bcrypt Generator", "/bcrypt-generator", ShieldCheck), tool("iban", "IBAN Validator", "/iban-validator", ShieldCheck), tool("base64", "Base64 String Converter", "/base64-string-converter", ShieldCheck), tool("basic-auth", "Basic Auth Generator", "/basic-auth-generator", ShieldCheck), tool("bip39", "BIP39 Generator", "/bip39-generator", ShieldCheck)
  ] },
  { slug: "converter-tools-dashboard", title: "Converter Tools Dashboard", titleKey: "converters", description: "Convert data, files, formats, and values quickly.", descriptionKey: "converterDescription", icon: Arrow, badgeCount: 19, tools: [
    tool("base64-file", "Base64 File Converter", "/base64-file-converter", Arrow), tool("case", "Case Converter", "/case-converter", Arrow), tool("url", "URL Encoder / Decoder", "/url-encoder-decoder", Arrow), tool("json-yaml", "JSON / YAML Converter", "/json-yaml-converter", Arrow), tool("json-xml", "JSON to XML Converter", "/json-to-xml-converter", Arrow), tool("xml-json", "XML to JSON Converter", "/xml-to-json-converter", Arrow), tool("toml-json", "TOML to JSON Converter", "/toml-to-json-converter", Arrow), tool("json-toml", "JSON to TOML Converter", "/json-to-toml-converter", Arrow), tool("toml-yaml", "TOML to YAML Converter", "/toml-to-yaml-converter", Arrow), tool("yaml-toml", "YAML to JSON / TOML", "/yaml-to-json-toml", Arrow), tool("yaml-prettify", "YAML Prettify", "/yaml-prettify", Arrow), tool("list", "List Converter", "/list-converter", Arrow), tool("integer-base", "Integer Base Converter", "/integer-base-converter", Arrow), tool("roman", "Roman Numeral Converter", "/roman-numeral-converter", Arrow), tool("temperature", "Temperature Converter", "/temperature-converter", Arrow), tool("color", "Color Converter", "/color-converter", Arrow), tool("text-binary", "Text to Binary", "/text-to-binary", Arrow), tool("ipv4-address", "IPv4 Address Converter", "/ipv4-address-converter", Arrow), tool("markdown", "Markdown to HTML", "/markdown-to-html", Arrow)
  ] },
  { slug: "web-tools-dashboard", title: "Web Tools Dashboard", titleKey: "web", description: "Inspect, test, and prepare modern web content.", descriptionKey: "webDescription", icon: Globe2, badgeCount: 14, tools: [
    tool("html", "HTML WYSIWYG Editor", "/html-wysiwyg-editor", Globe2), tool("user-agent", "User Agent Parser", "/user-agent-parser", Globe2), tool("url-parser", "URL Parser", "/url-parser", Globe2), tool("html-entities", "HTML Entities", "/html-entities", Globe2), tool("regex", "Regex Tester", "/regex-tester", Globe2), tool("http-status", "HTTP Status Codes", "/http-status-codes", Globe2), tool("mime", "MIME Types", "/mime-types", Globe2), tool("og-meta", "Open Graph Meta Generator", "/og-meta-generator", Globe2), tool("phone", "Phone Parser", "/phone-parser", Globe2), tool("email", "Email Normalizer", "/email-normalizer", Globe2), tool("slugify", "Slugify String", "/slugify-string", Globe2), tool("xml-format", "XML Formatter", "/xml-formatter", Globe2), tool("outlook", "Outlook Safelink Decoder", "/outlook-safelink-decoder", Globe2), tool("device", "Device Information", "/device-information", Globe2)
  ] },
  { slug: "developer-tools-dashboard", title: "Developer Tools Dashboard", titleKey: "developer", description: "Build, debug, format, and document software projects.", descriptionKey: "developerDescription", icon: Code2, badgeCount: 15, tools: [
    tool("uuid", "UUID Generator", "/uuid-generator", Code2), tool("cron", "Crontab Generator", "/crontab-generator", Code2), tool("json-format", "JSON Formatter / Minifier", "/json-formatter-minifier", Code2), tool("sql", "SQL Prettify", "/sql-prettify", Code2), tool("docker", "Docker Run to Compose", "/docker-run-to-docker-compose-converter", Code2), tool("chmod", "Chmod Calculator", "/chmod-calculator", Code2), tool("git", "Git Memo", "/git-memo", Code2), tool("keycode", "Keycode Info", "/keycode-info", Code2), tool("mac", "MAC Address Lookup", "/mac-address-lookup", Code2), tool("otp", "OTP Generator", "/otp-generator", Code2), tool("code", "Code Tools", "/tools", Code2), tool("json-diff", "JSON Diff", "/json-diff", Code2), tool("yaml-pretty", "YAML Prettify", "/yaml-prettify", Code2), tool("text-statistics", "Text Statistics", "/text-statistics", Code2), tool("string-obfuscator", "String Obfuscator", "/string-obfuscator", Code2)
  ] },
  { slug: "network-tools-dashboard", title: "Network Tools Dashboard", titleKey: "network", description: "Work with addresses, ports, protocols, and connectivity.", descriptionKey: "networkDescription", icon: Network, badgeCount: 10, tools: [
    tool("speed", "Speed Test", "/speed-test", Network), tool("subnet", "IPv4 Subnet Calculator", "/ipv4-subnet-calculator", Network), tool("ipv4-range", "IPv4 Range Expander", "/ipv4-range-expander", Network), tool("ipv6", "IPv6 ULA Generator", "/ipv6-ula-generator", Network), tool("random-port", "Random Port Generator", "/random-port-generator", Network), tool("wifi", "WiFi QR Generator", "/wifi-qr-code-generator", Network), tool("status", "HTTP Status Codes", "/http-status-codes", Network), tool("basic-auth", "Basic Auth Generator", "/basic-auth-generator", Network), tool("ip-converter", "IPv4 Address Converter", "/ipv4-address-converter", Network), tool("barcode", "Barcode Generator", "/barcode-generator", Network)
  ] },
  { slug: "text-data-dashboard", title: "Text & Data Dashboard", titleKey: "textData", description: "Transform, compare, generate, and analyze text.", descriptionKey: "textDataDescription", icon: Type, badgeCount: 16, tools: [
    tool("diff", "Text Diff Inspector", "/text-diff", Type), tool("notepad", "Online Notepad", "/notepad", Type), tool("lorem", "Lorem Ipsum Generator", "/lorem-ipsum-generator", Type), tool("typing", "Typing Speed Test", "/typing-speed", Type), tool("nato", "Text to NATO Alphabet", "/text-to-nato-alphabet", Type), tool("unicode", "Text to Unicode", "/text-to-unicode", Type), tool("nato-binary", "Text to Binary", "/text-to-binary", Type), tool("text-stats", "Text Statistics", "/text-statistics", Type), tool("obfuscate", "String Obfuscator", "/string-obfuscator", Type), tool("numeronym", "Numeronym Generator", "/numeronym-generator", Type), tool("emoji", "Emoji Picker", "/emoji-picker", Type), tool("list-converter", "List Converter", "/list-converter", Type), tool("slug", "Slugify String", "/slugify-string", Type), tool("json-diff", "JSON Diff", "/json-diff", Type), tool("ascii", "ASCII Art Generator", "/ascii-art-generator", Type), tool("git-memo", "Git Memo", "/git-memo", Type)
  ] },
  { slug: "math-media-dashboard", title: "Math & Media Dashboard", titleKey: "mathMedia", description: "Calculate, measure, record, and create media assets.", descriptionKey: "mathMediaDescription", icon: Calculator, badgeCount: 12, tools: [
    tool("percentage", "Percentage Calculator", "/percentage-calculator", Calculator), tool("eta", "ETA Calculator", "/eta-calculator", Calculator), tool("chronometer", "Chronometer", "/chronometer", Calculator), tool("camera", "Camera Recorder", "/camera-recorder", Calculator), tool("color-picker", "Color Picker", "/color-picker", Calculator), tool("svg", "SVG Placeholder Generator", "/svg-placeholder-generator", Calculator), tool("qr", "QR Code Generator", "/qr-generator", Calculator), tool("barcode-reader", "Barcode Reader", "/barcode-reader", Calculator), tool("image-converter", "Image Converter", "/image-converter", Calculator), tool("watermark", "Watermark Image", "/watermark-image", Calculator), tool("benchmark", "Benchmark Builder", "/benchmark-builder", Calculator), tool("integer", "Integer Base Converter", "/integer-base-converter", Calculator)
  ] }
];

export const dashboardBySlug = Object.fromEntries(DASHBOARD_CATEGORIES.map((category) => [category.slug, category])) as Record<string, DashboardCategory>;
export const allDashboardTools = DASHBOARD_CATEGORIES.flatMap((category) => category.tools.map((item) => ({ ...item, dashboard: category.slug })));
