export type RegexMatch = { index: number; value: string; captures: Array<{ name: string; value: string; start: number; end: number }>; groups: Array<{ name: string; value: string; start: number; end: number }> };

export function testRegex(pattern: string, text: string, flags: string) {
  const regex = new RegExp(pattern, flags.includes("g") ? flags : `${flags}g`);
  const matches: RegexMatch[] = [];
  let match: RegExpExecArray | null;
  while ((match = regex.exec(text))) {
    matches.push({ index: match.index, value: match[0], captures: match.slice(1).map((value, index) => ({ name: String(index + 1), value: value ?? "", start: value == null ? -1 : match!.index + match![0].indexOf(value), end: value == null ? -1 : match!.index + match![0].indexOf(value) + value.length })), groups: Object.entries(match.groups ?? {}).map(([name, value]) => ({ name, value: value ?? "", start: value == null ? -1 : match!.index + match![0].indexOf(value), end: value == null ? -1 : match!.index + match![0].indexOf(value) + value.length })) });
    if (!match[0]) regex.lastIndex += 1;
  }
  return matches;
}

function shellTokens(command: string) {
  const tokens: string[] = []; let current = ""; let quote = "";
  for (const char of command.trim().split("")) { if (quote) { if (char === quote) quote = ""; else current += char; } else if (char === "'" || char === '"') quote = char; else if (/\s/.test(char)) { if (current) { tokens.push(current); current = ""; } } else current += char; }
  if (current) tokens.push(current); return tokens;
}
function yamlQuote(value: string) { return /^[\w./:@+-]+$/.test(value) ? value : JSON.stringify(value); }
function yamlList(values: string[]) { return values.length ? `[${values.map(yamlQuote).join(", ")}]` : "[]"; }
export function dockerRunToCompose(command: string) {
  const tokens = shellTokens(command).filter(token => token !== "docker" && token !== "run");
  const service: Record<string, unknown> = {}; const ports: string[] = []; const volumes: string[] = []; const environment: string[] = []; const networks: string[] = []; const commandArgs: string[] = [];
  let image = ""; let detached = false; let i = 0;
  const takesValue = new Set(["-p", "--publish", "-v", "--volume", "-e", "--env", "--name", "--restart", "--network", "--hostname", "--user", "--workdir"]);
  while (i < tokens.length) { const token = tokens[i]; const next = tokens[i + 1]; if (token === "-d" || token === "--detach") detached = true; else if (token === "--rm") service.restart = "no"; else if (takesValue.has(token)) { i++; if (token === "-p" || token === "--publish") ports.push(next); else if (token === "-v" || token === "--volume") volumes.push(next); else if (token === "-e" || token === "--env") environment.push(next); else if (token === "--network") networks.push(next); else if (token === "--name") service.container_name = next; else if (token === "--restart") service.restart = next; else if (token === "--hostname") service.hostname = next; else if (token === "--user") service.user = next; else if (token === "--workdir") service.working_dir = next; } else if (token.startsWith("-")) { if (next && !next.startsWith("-")) { commandArgs.push(token, next); i++; } else commandArgs.push(token); } else if (!image) image = token; else commandArgs.push(token); i++; }
  if (!image) throw new Error("A Docker image is required"); service.image = image; if (ports.length) service.ports = yamlList(ports); if (volumes.length) service.volumes = yamlList(volumes); if (environment.length) service.environment = yamlList(environment); if (networks.length) service.networks = yamlList(networks); if (detached) service.detach = true; if (commandArgs.length) service.command = yamlList(commandArgs);
  const lines = ["services:", "  app:"]; for (const [key, value] of Object.entries(service)) { if (typeof value === "string" && value.startsWith("[")) lines.push(`    ${key}: ${value}`); else if (typeof value === "boolean") lines.push(`    ${key}: ${value}`); else lines.push(`    ${key}: ${yamlQuote(String(value))}`); } return lines.join("\n");
}

function scalar(value: string): unknown { const clean = value.trim().replace(/\s+#.*$/, ""); if (!clean) return {}; if (clean === "null" || clean === "~") return null; if (clean === "true") return true; if (clean === "false") return false; if (/^-?\d+(\.\d+)?$/.test(clean)) return Number(clean); if ((clean.startsWith('"') && clean.endsWith('"')) || (clean.startsWith("'") && clean.endsWith("'"))) return clean.slice(1, -1); if (clean.startsWith("[") && clean.endsWith("]")) return clean.slice(1, -1).split(",").map(item => scalar(item)); return clean; }
export function parseYaml(value: string): unknown { const lines = value.split(/\r?\n/).map(line => ({ indent: line.search(/\S|$/), text: line.trim() })).filter(line => line.text && !line.text.startsWith("#")); const parse = (start: number, indent: number): [unknown, number] => { const array = lines[start]?.text.startsWith("-"); const object: Record<string, unknown> = {}; const list: unknown[] = []; let index = start; while (index < lines.length && lines[index].indent === indent) { const line = lines[index].text; if (array) { if (!line.startsWith("-")) break; const content = line.slice(1).trim(); if (content.includes(": ")) { const [key, rest] = content.split(/:(.*)/s).slice(0, 2); const item: Record<string, unknown> = { [key.trim()]: scalar(rest) }; index++; while (index < lines.length && lines[index].indent > indent) { const nested = lines[index].text.split(/:(.*)/s); item[nested[0].trim()] = scalar(nested[1] ?? ""); index++; } list.push(item); } else { list.push(scalar(content)); index++; } } else { const match = line.match(/^([^:]+):(.*)$/); if (!match) throw new Error("Invalid YAML mapping"); const key = match[1].trim(); const rest = match[2].trim(); if (rest) { object[key] = scalar(rest); index++; } else if (index + 1 < lines.length && lines[index + 1].indent > indent) { const [child, next] = parse(index + 1, lines[index + 1].indent); object[key] = child; index = next; } else { object[key] = null; index++; } } } return [array ? list : object, index]; }; if (!lines.length) return null; return parse(0, lines[0].indent)[0]; }
export function yamlToJson(value: string) { return JSON.stringify(parseYaml(value), null, 2); }
function tomlScalar(value: unknown) { if (typeof value === "string") return JSON.stringify(value); if (value === null) return ""; return String(value); }
export function yamlToToml(value: string) { const data = parseYaml(value); if (!data || typeof data !== "object" || Array.isArray(data)) throw new Error("TOML requires a top-level mapping"); const lines: string[] = []; const write = (object: Record<string, unknown>, prefix = "") => { for (const [key, entry] of Object.entries(object)) if (entry && typeof entry === "object" && !Array.isArray(entry)) { lines.push(`[${prefix}${key}]`); write(entry as Record<string, unknown>, `${prefix}${key}.`); } else lines.push(`${key} = ${Array.isArray(entry) ? `[${entry.map(tomlScalar).join(", ")}]` : tomlScalar(entry)}`); }; write(data as Record<string, unknown>); return lines.join("\n"); }

export function escapeHtml(value: string) { return value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;"); }
function inlineMarkdown(value: string) { return escapeHtml(value).replace(/`([^`]+)`/g, "<code>$1</code>").replace(/\*\*([^*]+)\*\*/g, "<strong>$1</strong>").replace(/__([^_]+)__/g, "<strong>$1</strong>").replace(/\*([^*]+)\*/g, "<em>$1</em>").replace(/_([^_]+)_/g, "<em>$1</em>").replace(/\[([^\]]+)\]\((https?:\/\/[^\s)]+)\)/g, '<a href="$2" rel="noreferrer noopener">$1</a>'); }
export function markdownToHtml(markdown: string) { const lines = markdown.replace(/\r/g, "").split("\n"); const output: string[] = []; let inCode = false; let list = ""; let table = false; for (const line of lines) { if (line.startsWith("```") ) { if (inCode) { output.push("</code></pre>"); inCode = false; } else { output.push("<pre><code>"); inCode = true; } continue; } if (inCode) { output.push(escapeHtml(line) + "\n"); continue; } if (/^\|.*\|$/.test(line)) { if (/^\|\s*:?-+/.test(line)) continue; if (!table) { output.push("<table><tbody>"); table = true; } output.push(`<tr>${line.split("|").slice(1, -1).map(cell => `<td>${inlineMarkdown(cell.trim())}</td>`).join("")}</tr>`); continue; } if (table) { output.push("</tbody></table>"); table = false; } const heading = line.match(/^(#{1,6})\s+(.+)$/); if (heading) { output.push(`<h${heading[1].length}>${inlineMarkdown(heading[2])}</h${heading[1].length}>`); continue; } const bullet = line.match(/^\s*[-*+]\s+(.+)$/); if (bullet) { if (!list) { output.push("<ul>"); list = "ul"; } output.push(`<li>${inlineMarkdown(bullet[1])}</li>`); continue; } if (list) { output.push(`</${list}>`); list = ""; } if (line.trim()) output.push(`<p>${inlineMarkdown(line)}</p>`); } if (list) output.push(`</${list}>`); if (table) output.push("</tbody></table>"); return output.join("\n"); }
export function sanitizeHtml(value: string) { return value.replace(/<\/?(script|style|iframe|object|embed|form)(?:\s[^>]*)?>/gi, "").replace(/\s(on\w+|style|srcdoc)\s*=\s*(?:"[^"]*"|'[^']*')/gi, ""); }
