export type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };

function splitTop(value: string, delimiter: string) {
  const parts: string[] = []; let start = 0; let depth = 0; let quote = "";
  for (let i = 0; i < value.length; i += 1) { const char = value[i]; if ((char === '"' || char === "'") && value[i - 1] !== "\\") quote = quote === char ? "" : quote || char; if (!quote && "[{".includes(char)) depth += 1; if (!quote && "]}".includes(char)) depth -= 1; if (!quote && depth === 0 && char === delimiter) { parts.push(value.slice(start, i).trim()); start = i + 1; } }
  parts.push(value.slice(start).trim()); return parts.filter(Boolean);
}
function stripComment(line: string) { const index = line.indexOf("#"); return index < 0 ? line : line.slice(0, index); }
function tomlValue(value: string): JsonValue { const item = value.trim(); if ((item.startsWith('"') && item.endsWith('"')) || (item.startsWith("'") && item.endsWith("'"))) return item.slice(1, -1); if (item === "true" || item === "false") return item === "true"; if (item !== "" && !Number.isNaN(Number(item))) return Number(item.split("_").join("")); if (item.startsWith("[") && item.endsWith("]")) return splitTop(item.slice(1, -1), ",").map(tomlValue); if (item.startsWith("{") && item.endsWith("}")) return Object.fromEntries(splitTop(item.slice(1, -1), ",").map((entry) => { const index = entry.indexOf("="); return [entry.slice(0, index).trim(), tomlValue(entry.slice(index + 1))]; })); return item; }
function setPath(target: Record<string, JsonValue>, path: string[], value: JsonValue) { let current = target; path.forEach((key, index) => { if (index === path.length - 1) current[key] = value; else { if (!current[key] || typeof current[key] !== "object" || Array.isArray(current[key])) current[key] = {}; current = current[key] as Record<string, JsonValue>; } }); }
function parseToml(input: string): JsonValue { const result: Record<string, JsonValue> = {}; let section: string[] = []; for (const raw of input.split(/\r?\n/)) { const line = stripComment(raw).trim(); if (!line) continue; if (line.startsWith("[[")) throw new Error("Array tables are not supported"); if (line.startsWith("[") && line.endsWith("]")) { section = line.slice(1, -1).split(".").map((part) => part.trim()); continue; } const index = line.indexOf("="); if (index < 1) throw new Error("Invalid TOML assignment"); setPath(result, [...section, line.slice(0, index).trim()], tomlValue(line.slice(index + 1))); } return result; }
function yamlScalar(value: JsonValue) { if (typeof value === "string") return /^[A-Za-z0-9 _./:@+-]+$/.test(value) && !["true", "false", "null"].includes(value) ? value : JSON.stringify(value); if (value === null) return "null"; return String(value); }
function stringifyYaml(value: JsonValue, indent: 2 | 4, depth = 0): string { const pad = " ".repeat(depth * indent); if (Array.isArray(value)) return value.length ? value.map((item) => `${pad}- ${typeof item === "object" && item !== null ? "\n" + stringifyYaml(item, indent, depth + 1) : yamlScalar(item)}`).join("\n") : `${pad}[]`; if (value !== null && typeof value === "object") return Object.entries(value).map(([key, item]) => `${pad}${key}:${typeof item === "object" && item !== null ? "\n" + stringifyYaml(item, indent, depth + 1) : ` ${yamlScalar(item)}`}`).join("\n") || `${pad}{}`; return `${pad}${yamlScalar(value)}`; }
export function tomlToYaml(input: string, indent: 2 | 4 = 2) { return input.trim() ? stringifyYaml(parseToml(input), indent) : ""; }

function yamlValue(value: string): JsonValue { const item = value.trim(); if (item === "null" || item === "~") return null; if (item === "true" || item === "false") return item === "true"; if (item !== "" && !Number.isNaN(Number(item))) return Number(item); if ((item.startsWith('"') && item.endsWith('"')) || (item.startsWith("'") && item.endsWith("'"))) return item.slice(1, -1); if (item.startsWith("[") || item.startsWith("{")) { try { return JSON.parse(item.split("'").join('"')) as JsonValue; } catch { throw new Error("Invalid YAML inline value"); } } return item; }
export function parseYaml(input: string): JsonValue { const root: Record<string, JsonValue> = {}; const stack: { indent: number; value: Record<string, JsonValue> }[] = [{ indent: -1, value: root }]; for (const line of input.split(/\r?\n/).map(stripComment).filter((item) => item.trim())) { const indent = line.length - line.trimStart().length; while (stack.length > 1 && indent <= stack[stack.length - 1].indent) stack.pop(); const current = stack[stack.length - 1].value; const index = line.indexOf(":"); if (index < 1) throw new Error("Invalid YAML mapping"); const key = line.slice(indent, index).trim(); const raw = line.slice(index + 1).trim(); if (raw) current[key] = yamlValue(raw); else { const child: Record<string, JsonValue> = {}; current[key] = child; stack.push({ indent, value: child }); } } return root; }
export function prettifyYaml(input: string, indent: 2 | 4, minify: boolean) { const parsed = parseYaml(input); return minify ? JSON.stringify(parsed) : stringifyYaml(parsed, indent); }

export type EmailDetails = { original: string; normalized: string; localPart: string; domain: string; provider: string; disposable: boolean };
const disposableDomains = new Set(["mailinator.com", "10minutemail.com", "guerrillamail.com", "tempmail.com", "yopmail.com", "dispostable.com"]);
export function normalizeEmail(input: string): EmailDetails { const original = input.trim(); const match = original.match(/^([^@\\s]+)@([^@\\s]+)$/); if (!match) throw new Error(`Invalid email: ${input}`); let localPart = match[1]; const domain = match[2].toLowerCase(); const provider = domain.split(".")[0]; if (["gmail.com", "googlemail.com"].includes(domain)) localPart = localPart.split("+")[0].split(".").join(""); else if (["outlook.com", "hotmail.com", "live.com", "msn.com", "yahoo.com"].includes(domain)) localPart = localPart.split("+")[0]; return { original, normalized: `${localPart}@${domain}`, localPart, domain, provider, disposable: disposableDomains.has(domain) }; }

export type BenchmarkResult = { name: string; duration: number; opsPerSecond: number; percentFromFastest: number };
export function runBenchmarks(snippets: { name: string; code: string }[], iterations: number): BenchmarkResult[] { if (!Number.isInteger(iterations) || iterations < 1 || iterations > 10000000) throw new Error("Iterations must be between 1 and 10,000,000"); const results = snippets.map(({ name, code }) => { const run = new Function(code); const start = performance.now(); for (let index = 0; index < iterations; index += 1) run(); const duration = performance.now() - start; return { name: name || "Unnamed", duration, opsPerSecond: duration > 0 ? iterations / (duration / 1000) : Infinity, percentFromFastest: 0 }; }); const fastest = Math.min(...results.map((result) => result.duration)); return results.map((result) => ({ ...result, percentFromFastest: fastest > 0 ? ((result.duration - fastest) / fastest) * 100 : 0 })).sort((a, b) => a.duration - b.duration); }
