import QRCode from "qrcode";
export type WifiSecurity = "nopass" | "WPA" | "WEP";
function wifiEscape(value: string) { return value.replace(/([\\;,:\"])/g, "\\$1"); }
export function wifiUri(ssid: string, password: string, security: WifiSecurity, hidden: boolean) { if (!ssid) return ""; if (security === "nopass") return `WIFI:S:${wifiEscape(ssid)};${hidden ? "H:true;" : ""};`; return `WIFI:S:${wifiEscape(ssid)};T:${security};P:${wifiEscape(password)};${hidden ? "H:true;" : ""};`; }
export async function wifiQrDataUrl(value: string, dark: string, light: string) { return value ? QRCode.toDataURL(value, { width: 600, margin: 2, errorCorrectionLevel: "M", color: { dark, light } }) : ""; }
export function svgPlaceholder(width: number, height: number, fontSize: number, background: string, foreground: string, customText: string, exactSize: boolean) { const text = customText || `${width}x${height}`; const safeText = text.replace(/[&<>\"]/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "\"": "&quot;" }[char] || char)); return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} ${height}"${exactSize ? ` width="${width}" height="${height}"` : ""}><rect width="${width}" height="${height}" fill="${background}"/><text x="50%" y="50%" dominant-baseline="middle" text-anchor="middle" font-family="monospace" font-size="${fontSize}px" fill="${foreground}">${safeText}</text></svg>`; }
export function svgDataUri(svg: string) { let binary = ""; new TextEncoder().encode(svg).forEach(byte => { binary += String.fromCharCode(byte); }); return `data:image/svg+xml;base64,${btoa(binary)}`; }
export type Color = { r: number; g: number; b: number; a: number };
const clamp = (value: number, min = 0, max = 1) => Math.min(max, Math.max(min, value));
export function parseHex(value: string): Color | null { const hex = value.trim().replace(/^#/, ""); if (![3, 4, 6, 8].includes(hex.length) || !/^[\da-f]+$/i.test(hex)) return null; const expanded = hex.length < 5 ? hex.split("").map(x => x + x).join("") : hex; return { r: parseInt(expanded.slice(0, 2), 16), g: parseInt(expanded.slice(2, 4), 16), b: parseInt(expanded.slice(4, 6), 16), a: expanded.length === 8 ? parseInt(expanded.slice(6, 8), 16) / 255 : 1 }; }
export function colorToHex(c: Color) { const hex = [c.r, c.g, c.b].map(x => Math.round(x).toString(16).padStart(2, "0")).join(""); return c.a < 1 ? `#${hex}${Math.round(c.a * 255).toString(16).padStart(2, "0")}` : `#${hex}`; }
export function colorToRgb(c: Color) { return c.a < 1 ? `rgba(${Math.round(c.r)}, ${Math.round(c.g)}, ${Math.round(c.b)}, ${Number(c.a.toFixed(3))})` : `rgb(${Math.round(c.r)}, ${Math.round(c.g)}, ${Math.round(c.b)})`; }
export function colorToHsl(c: Color) { const r = c.r / 255, g = c.g / 255, b = c.b / 255, max = Math.max(r, g, b), min = Math.min(r, g, b); let h = 0, s = 0; const l = (max + min) / 2; if (max !== min) { const d = max - min; s = l > .5 ? d / (2 - max - min) : d / (max + min); h = max === r ? (g - b) / d + (g < b ? 6 : 0) : max === g ? (b - r) / d + 2 : (r - g) / d + 4; h *= 60; } return `hsla(${Math.round(h)}, ${Math.round(s * 100)}%, ${Math.round(l * 100)}%, ${Number(c.a.toFixed(3))})`; }
export function colorToHsv(c: Color) { const r = c.r / 255, g = c.g / 255, b = c.b / 255, max = Math.max(r, g, b), min = Math.min(r, g, b), d = max - min; let h = 0; if (d) h = max === r ? ((g - b) / d) % 6 : max === g ? (b - r) / d + 2 : (r - g) / d + 4; if (h < 0) h += 6; return `hsva(${Math.round(h * 60)}, ${Math.round((max ? d / max : 0) * 100)}%, ${Math.round(max * 100)}%, ${Number(c.a.toFixed(3))})`; }
export function colorToCmyk(c: Color) { const r = c.r / 255, g = c.g / 255, b = c.b / 255, k = 1 - Math.max(r, g, b); const divisor = 1 - k || 1; return `cmyka(${Math.round((1 - r - k) / divisor * 100)}%, ${Math.round((1 - g - k) / divisor * 100)}%, ${Math.round((1 - b - k) / divisor * 100)}%, ${Math.round(k * 100)}%, ${Number(c.a.toFixed(3))})`; }
export function parseColor(value: string, format: "hex" | "rgb" | "hsl" | "hsv" | "cmyk") { if (format === "hex") return parseHex(value); const numbers = value.match(/-?[\d.]+/g)?.map(Number); if (!numbers) return null; if (format === "rgb" && numbers.length >= 3) return { r: numbers[0], g: numbers[1], b: numbers[2], a: numbers[3] ?? 1 }; if (format === "hsl" && numbers.length >= 3) { const h = numbers[0] / 360, s = numbers[1] / 100, l = numbers[2] / 100; const hue = (n: number) => { const k = (n + h * 12) % 12; return l - s * Math.min(l, 1 - l) * Math.max(-1, Math.min(k - 3, 9 - k, 1)); }; return { r: hue(0) * 255, g: hue(8) * 255, b: hue(4) * 255, a: numbers[3] ?? 1 }; } if (format === "hsv" && numbers.length >= 3) { const h = numbers[0] / 60, s = numbers[1] / 100, v = numbers[2] / 100, f = (n: number) => v - v * s * Math.max(0, Math.min((n + h) % 6, 4 - (n + h) % 6, 1)); return { r: f(5) * 255, g: f(3) * 255, b: f(1) * 255, a: numbers[3] ?? 1 }; } if (format === "cmyk" && numbers.length >= 4) { const [c, m, y, k] = numbers.slice(0, 4).map(n => n / 100); return { r: 255 * (1 - c) * (1 - k), g: 255 * (1 - m) * (1 - k), b: 255 * (1 - y) * (1 - k), a: numbers[4] ?? 1 }; } return null; }
const entities: Record<string, string> = { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" };
export function escapeHtmlEntities(value: string) { return value.replace(/[&<>"']/g, char => entities[char]); }
export function unescapeHtmlEntities(value: string) { const named: Record<string, string> = { amp: "&", lt: "<", gt: ">", quot: '"', apos: "'", nbsp: " " }; return value.replace(/&(#\d+|#x[\da-f]+|[a-z]+);/gi, (_, entity: string) => entity.startsWith("#x") ? String.fromCodePoint(parseInt(entity.slice(2), 16)) : entity.startsWith("#") ? String.fromCodePoint(parseInt(entity.slice(1), 10)) : named[entity.toLowerCase()] ?? `&${entity};`); }
