export type SubnetInfo = { cidr: string; netmask: string; network: string; broadcast: string; wildcard: string; firstUsable: string; lastUsable: string; totalUsable: number; prefix: number; ipClass: string };
function ipToNumber(ip: string) { const parts = ip.split(".").map(Number); if (parts.length !== 4 || parts.some((part) => !Number.isInteger(part) || part < 0 || part > 255)) throw new Error("Invalid IPv4 address"); return (((parts[0] * 256 + parts[1]) * 256 + parts[2]) * 256 + parts[3]) >>> 0; }
function numberToIp(value: number) { return [value >>> 24, (value >>> 16) & 255, (value >>> 8) & 255, value & 255].join("."); }
export function calculateSubnet(value: string): SubnetInfo { const [rawIp, rawPrefix] = value.trim().split("/"); const ip = ipToNumber(rawIp); const prefix = rawPrefix === undefined || rawPrefix === "" ? 32 : Number(rawPrefix); if (!Number.isInteger(prefix) || prefix < 0 || prefix > 32) throw new Error("Invalid CIDR prefix"); const mask = prefix === 0 ? 0 : (0xffffffff << (32 - prefix)) >>> 0; const network = (ip & mask) >>> 0; const wildcard = (~mask) >>> 0; const broadcast = (network | wildcard) >>> 0; const usable = prefix >= 31 ? 0 : Math.max(0, broadcast - network - 1); const first = prefix >= 31 ? network : network + 1; const last = prefix >= 31 ? broadcast : broadcast - 1; const firstOctet = network >>> 24; return { cidr: `${numberToIp(network)}/${prefix}`, netmask: numberToIp(mask), network: numberToIp(network), broadcast: numberToIp(broadcast), wildcard: numberToIp(wildcard), firstUsable: numberToIp(first), lastUsable: numberToIp(last), totalUsable: usable, prefix, ipClass: firstOctet < 128 ? "A" : firstOctet < 192 ? "B" : firstOctet < 224 ? "C" : firstOctet < 240 ? "D" : "E" }; }
export function shiftSubnet(value: string, count: number) { const info = calculateSubnet(value); const next = (ipToNumber(info.network) + count * (2 ** (32 - info.prefix))) >>> 0; return `${numberToIp(next)}/${info.prefix}`; }

export type CronFields = { minute: string; hour: string; day: string; month: string; weekday: string };
export function parseCron(value: string): { valid: boolean; fields: CronFields; explanation: string } { const aliases: Record<string, string> = { "@hourly": "0 * * * *", "@daily": "0 0 * * *", "@midnight": "0 0 * * *", "@weekly": "0 0 * * 0", "@monthly": "0 0 1 * *", "@yearly": "0 0 1 1 *", "@annually": "0 0 1 1 *" }; const normalized = aliases[value.trim().toLowerCase()] || value.trim(); const parts = normalized.split(/\s+/); const fields = { minute: parts[0] || "", hour: parts[1] || "", day: parts[2] || "", month: parts[3] || "", weekday: parts[4] || "" }; const valid = parts.length === 5 && /^([\d*/?,\-]+)$/.test(normalized); const explanation = valid ? `At ${fields.minute === "*" ? "every minute" : `minute ${fields.minute}`} ${fields.hour === "*" ? "of every hour" : `of hour ${fields.hour}`} ${fields.day === "*" ? "on every day" : `on day ${fields.day}`} ${fields.month === "*" ? "of every month" : `of month ${fields.month}`} ${fields.weekday === "*" ? "on every weekday" : `on weekday ${fields.weekday}`}.` : ""; return { valid, fields, explanation }; }
export function buildCron(fields: CronFields) { return [fields.minute, fields.hour, fields.day, fields.month, fields.weekday].join(" "); }

export function formatJson(value: string, indent: "2" | "4" | "tab") { const parsed = JSON.parse(value); return JSON.stringify(parsed, null, indent === "tab" ? "\t" : Number(indent)); }
export function minifyJson(value: string) { return JSON.stringify(JSON.parse(value)); }
const sqlKeywords = /\b(SELECT|FROM|WHERE|JOIN|LEFT JOIN|RIGHT JOIN|INNER JOIN|OUTER JOIN|ON|GROUP BY|ORDER BY|HAVING|LIMIT|UNION|VALUES|SET|INSERT INTO|UPDATE|DELETE FROM|CREATE TABLE|AND|OR)\b/gi;
export function prettifySql(value: string) { let sql = value.replace(/\s+/g, " ").trim().replace(/\s*,\s*/g, ", "); sql = sql.replace(sqlKeywords, (keyword) => `\n${keyword.toUpperCase()}`); sql = sql.replace(/\n(AND|OR)\b/g, "\n  $1"); sql = sql.replace(/\n/g, "\n").trim(); return sql; }
