export type TextStats = { characters: number; words: number; sentences: number; lines: number; paragraphs: number; readingMinutes: number; speakingMinutes: number; bytes: number; frequency: Array<{ character: string; count: number; percentage: number }> };

export function textStatistics(value: string): TextStats { const words = value.trim() ? value.trim().split(/\s+/).length : 0; const frequencies = new Map<string, number>(); for (const character of value.toLocaleLowerCase()) if (/\S/.test(character)) frequencies.set(character, (frequencies.get(character) || 0) + 1); return { characters: value.length, words, sentences: value.trim() ? (value.match(/[.!?]+(?:\s|$)/g) || []).length || 1 : 0, lines: value ? value.split(/\r\n|\r|\n/).length : 0, paragraphs: value.trim() ? value.trim().split(/\n\s*\n/).length : 0, readingMinutes: words / 200, speakingMinutes: words / 130, bytes: new TextEncoder().encode(value).byteLength, frequency: [...frequencies.entries()].sort((a, b) => b[1] - a[1]).map(([character, count]) => ({ character, count, percentage: value.length ? count / value.length * 100 : 0 })) }; }

export function obfuscateHex(value: string) { return Array.from(value, character => character.codePointAt(0)!.toString(16).padStart(2, "0")).join(" "); }
export function obfuscateCharCode(value: string) { return `String.fromCharCode(${Array.from(value, character => character.codePointAt(0)).join(", ")})`; }
export function obfuscateHtml(value: string) { return Array.from(value, character => `&#${character.codePointAt(0)};`).join(""); }
export function obfuscateBase64(value: string) { const bytes = new TextEncoder().encode(value); let binary = ""; bytes.forEach(byte => { binary += String.fromCharCode(byte); }); const encoded = btoa(binary); return `eval(atob(${JSON.stringify(encoded)}))`; }

export function createNumeronym(value: string, minimumLength = 4) { return value.split(/(\s+)/).map(part => { if (/^\s+$/.test(part) || part.length < minimumLength) return part; return `${part[0]}${[...part].length - 2}${part.at(-1)}`; }).join(""); }

const countryCodes: Record<string, string> = { "1": "United States / Canada", "7": "Russia / Kazakhstan", "20": "Egypt", "27": "South Africa", "30": "Greece", "31": "Netherlands", "32": "Belgium", "33": "France", "34": "Spain", "36": "Hungary", "39": "Italy", "40": "Romania", "41": "Switzerland", "43": "Austria", "44": "United Kingdom", "45": "Denmark", "46": "Sweden", "47": "Norway", "48": "Poland", "49": "Germany", "51": "Peru", "52": "Mexico", "53": "Cuba", "54": "Argentina", "55": "Brazil", "56": "Chile", "57": "Colombia", "58": "Venezuela", "60": "Malaysia", "61": "Australia", "62": "Indonesia", "63": "Philippines", "64": "New Zealand", "65": "Singapore", "66": "Thailand", "81": "Japan", "82": "South Korea", "84": "Vietnam", "86": "China", "90": "Turkey", "91": "India", "92": "Pakistan", "93": "Afghanistan", "94": "Sri Lanka", "95": "Myanmar", "98": "Iran", "212": "Morocco", "213": "Algeria", "216": "Tunisia", "218": "Libya", "234": "Nigeria", "254": "Kenya", "971": "United Arab Emirates", "972": "Israel", "973": "Bahrain", "974": "Qatar", "966": "Saudi Arabia", "977": "Nepal" };
export type PhoneDetails = { valid: boolean; possible: boolean; digits: string; countryCode: string; country: string; nationalPrefix: string; international: string; national: string; e164: string; rfc3966: string; error?: string };
export function parsePhone(value: string): PhoneDetails { const cleaned = value.trim().replace(/[().\-\s]/g, ""); const validCharacters = /^\+\d+$/.test(cleaned); const digits = cleaned.replace(/^\+/, ""); const code = Object.keys(countryCodes).sort((a, b) => b.length - a.length).find(candidate => digits.startsWith(candidate)) || ""; const national = code ? digits.slice(code.length) : digits; const possible = validCharacters && digits.length >= 7 && digits.length <= 15; const valid = possible && Boolean(code) && national.length >= 4; const international = code ? `+${code} ${national.replace(/(\d{3})(?=\d)/g, "$1 ").trim()}` : value; const nationalFormatted = national.replace(/(\d{3})(?=\d)/g, "$1 ").trim(); return { valid, possible, digits, countryCode: code ? `+${code}` : "", country: code ? countryCodes[code] : "Unknown", nationalPrefix: national.slice(0, 3), international, national: nationalFormatted ? `0${nationalFormatted}` : "", e164: valid ? `+${digits}` : "", rfc3966: valid ? `tel:+${digits}` : "", ...(validCharacters ? {} : { error: "Use an international number beginning with + and digits." }) }; }
