export type TotpAlgorithm = "SHA-1" | "SHA-256";
const base32Alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ234567";

export function normalizeBase32(value: string) { return value.replace(/[\s=-]/g, "").toUpperCase(); }
export function generateBase32Secret(length = 32) { const bytes = new Uint8Array(Math.ceil(length * 5 / 8)); crypto.getRandomValues(bytes); let bits = 0; let buffer = 0; let output = ""; for (const byte of bytes) { buffer = (buffer << 8) | byte; bits += 8; while (bits >= 5 && output.length < length) { bits -= 5; output += base32Alphabet[(buffer >> bits) & 31]; } } return output.padEnd(length, "A"); }
function base32Decode(value: string) { const normalized = normalizeBase32(value); if (!normalized || !/^[A-Z2-7]+$/.test(normalized)) throw new Error("Invalid Base32 secret"); const output = new Uint8Array(Math.floor(normalized.length * 5 / 8)); let buffer = 0; let bits = 0; let index = 0; for (const character of normalized) { buffer = (buffer << 5) | base32Alphabet.indexOf(character); bits += 5; if (bits >= 8 && index < output.length) { bits -= 8; output[index++] = (buffer >> bits) & 255; } } return output; }
export async function generateTotp(secret: string, algorithm: TotpAlgorithm, digits: 6 | 8, timestamp = Date.now(), step = 30) { const key = await crypto.subtle.importKey("raw", base32Decode(secret), { name: "HMAC", hash: algorithm }, false, ["sign"]); const counter = Math.floor(timestamp / 1000 / step); const message = new ArrayBuffer(8); const view = new DataView(message); view.setUint32(4, counter); const hash = new Uint8Array(await crypto.subtle.sign("HMAC", key, message)); const offset = hash[hash.length - 1] & 15; const binary = ((hash[offset] & 127) << 24) | (hash[offset + 1] << 16) | (hash[offset + 2] << 8) | hash[offset + 3]; return String(binary % 10 ** digits).padStart(digits, "0"); }
export function otpProgress(timestamp = Date.now(), step = 30) { const elapsed = Math.floor(timestamp / 1000) % step; return { remaining: step - elapsed, percentage: (step - elapsed) / step * 100 }; }

export type HttpStatus = { code: number; name: string; category: string; description: string };
export const httpStatuses: HttpStatus[] = [
  { code: 100, name: "Continue", category: "Informational", description: "The server has received the request headers and the client should proceed with the request body." }, { code: 101, name: "Switching Protocols", category: "Informational", description: "The server is switching protocols as requested by the client." }, { code: 102, name: "Processing", category: "Informational", description: "The server has received and is processing the request, but no response is available yet." },
  { code: 200, name: "OK", category: "Success", description: "The request succeeded." }, { code: 201, name: "Created", category: "Success", description: "The request succeeded and a new resource was created." }, { code: 202, name: "Accepted", category: "Success", description: "The request has been accepted for processing, but processing is not complete." }, { code: 204, name: "No Content", category: "Success", description: "The server successfully fulfilled the request and has no additional content to send." }, { code: 206, name: "Partial Content", category: "Success", description: "The server is delivering only part of the resource because of a range request." },
  { code: 300, name: "Multiple Choices", category: "Redirection", description: "The request has more than one possible response." }, { code: 301, name: "Moved Permanently", category: "Redirection", description: "The resource has been permanently moved to a new URL." }, { code: 302, name: "Found", category: "Redirection", description: "The resource temporarily resides at a different URL." }, { code: 304, name: "Not Modified", category: "Redirection", description: "The resource has not changed since the version specified by the request headers." }, { code: 307, name: "Temporary Redirect", category: "Redirection", description: "The request should be repeated at another URL without changing the method." }, { code: 308, name: "Permanent Redirect", category: "Redirection", description: "The resource has been permanently moved and the request method must be preserved." },
  { code: 400, name: "Bad Request", category: "Client Error", description: "The server cannot process the request because it is malformed or invalid." }, { code: 401, name: "Unauthorized", category: "Client Error", description: "Authentication is required or has failed." }, { code: 403, name: "Forbidden", category: "Client Error", description: "The server understood the request but refuses to authorize it." }, { code: 404, name: "Not Found", category: "Client Error", description: "The requested resource could not be found." }, { code: 405, name: "Method Not Allowed", category: "Client Error", description: "The request method is known but is not supported by the target resource." }, { code: 406, name: "Not Acceptable", category: "Client Error", description: "The server cannot produce a response matching the acceptable values in the request headers." }, { code: 408, name: "Request Timeout", category: "Client Error", description: "The server timed out waiting for the request." }, { code: 409, name: "Conflict", category: "Client Error", description: "The request conflicts with the current state of the target resource." }, { code: 410, name: "Gone", category: "Client Error", description: "The target resource is no longer available and will not be available again." }, { code: 415, name: "Unsupported Media Type", category: "Client Error", description: "The request content format is not supported by the server." }, { code: 422, name: "Unprocessable Content", category: "Client Error", description: "The request is well-formed but contains semantic errors." }, { code: 429, name: "Too Many Requests", category: "Client Error", description: "The client has sent too many requests in a given amount of time." },
  { code: 500, name: "Internal Server Error", category: "Server Error", description: "The server encountered an unexpected condition that prevented it from fulfilling the request." }, { code: 501, name: "Not Implemented", category: "Server Error", description: "The server does not support the functionality required to fulfill the request." }, { code: 502, name: "Bad Gateway", category: "Server Error", description: "The server received an invalid response from an upstream server." }, { code: 503, name: "Service Unavailable", category: "Server Error", description: "The server is not ready to handle the request, commonly because of maintenance or overload." }, { code: 504, name: "Gateway Timeout", category: "Server Error", description: "The server did not receive a timely response from an upstream server." }, { code: 505, name: "HTTP Version Not Supported", category: "Server Error", description: "The HTTP version used in the request is not supported by the server." },
];

export const mimeTypes: Array<{ extension: string; mime: string }> = ["html:text/html", "css:text/css", "js:text/javascript", "json:application/json", "xml:application/xml", "pdf:application/pdf", "zip:application/zip", "txt:text/plain", "csv:text/csv", "png:image/png", "jpg:image/jpeg", "jpeg:image/jpeg", "gif:image/gif", "svg:image/svg+xml", "webp:image/webp", "ico:image/x-icon", "mp3:audio/mpeg", "wav:audio/wav", "mp4:video/mp4", "webm:video/webm", "woff:font/woff", "woff2:font/woff2", "ttf:font/ttf", "doc:application/msword", "docx:application/vnd.openxmlformats-officedocument.wordprocessingml.document", "xls:application/vnd.ms-excel", "xlsx:application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "wasm:application/wasm"].map(value => { const [extension, mime] = value.split(":"); return { extension, mime }; });
