export type JwtClaim = { claim: string; value: string; description?: string; friendlyValue?: string };
export type JwtResult = { header: JwtClaim[]; payload: JwtClaim[]; valid: boolean; expired?: boolean; error?: string };
const claimDescriptions: Record<string, string> = { alg: "Algorithm", typ: "Type", sub: "Subject", iss: "Issuer", aud: "Audience", exp: "Expiration time", nbf: "Not before", iat: "Issued at", jti: "JWT ID" };
const algorithmDescriptions: Record<string, string> = { HS256: "HMAC using SHA-256", HS384: "HMAC using SHA-384", HS512: "HMAC using SHA-512", RS256: "RSA using SHA-256", ES256: "ECDSA using SHA-256" };
function decodeBase64Url(value: string) { const normalized = value.replace(/-/g, "+").replace(/_/g, "/"); const padded = normalized + "=".repeat((4 - normalized.length % 4) % 4); const binary = atob(padded); return new TextDecoder().decode(Uint8Array.from(binary, (char) => char.charCodeAt(0))); }
function friendlyClaim(claim: string, value: unknown) { if (["exp", "nbf", "iat"].includes(claim) && typeof value === "number") return new Date(value * 1000).toLocaleString(); if (claim === "alg" && typeof value === "string") return algorithmDescriptions[value]; return undefined; }
function claims(record: Record<string, unknown>) { return Object.entries(record).map(([claim, value]) => ({ claim, value: typeof value === "object" && value !== null ? JSON.stringify(value, null, 2) : String(value), description: claimDescriptions[claim], friendlyValue: friendlyClaim(claim, value) })); }
export function parseJwt(token: string): JwtResult { const empty = { header: [], payload: [], valid: false } as JwtResult; const parts = token.trim().split("."); if (parts.length !== 3) return { ...empty, error: "Invalid JWT format" }; try { const header = JSON.parse(decodeBase64Url(parts[0])) as Record<string, unknown>; const payload = JSON.parse(decodeBase64Url(parts[1])) as Record<string, unknown>; const expired = typeof payload.exp === "number" && payload.exp < Date.now() / 1000; return { header: claims(header), payload: claims(payload), valid: true, expired }; } catch { return { ...empty, error: "Unable to decode JWT" }; } }

export type UserAgentInfo = { browser: { name: string; version: string }; os: { name: string; version: string }; engine: { name: string; version: string }; device: { type: string; model: string; vendor: string } };
const unknown = "Unknown";
export function parseUserAgent(userAgent: string): UserAgentInfo { const ua = userAgent.trim(); let browser = { name: unknown, version: unknown }; if (/Edg\/([\d.]+)/.test(ua)) browser = { name: "Edge", version: RegExp.$1 }; else if (/OPR\/([\d.]+)/.test(ua)) browser = { name: "Opera", version: RegExp.$1 }; else if (/Chrome\/([\d.]+)/.test(ua)) browser = { name: "Chrome", version: RegExp.$1 }; else if (/Firefox\/([\d.]+)/.test(ua)) browser = { name: "Firefox", version: RegExp.$1 }; else if (/Version\/([\d.]+).*Safari/.test(ua)) browser = { name: "Safari", version: RegExp.$1 }; else if (/MSIE\s([\d.]+)/.test(ua)) browser = { name: "Internet Explorer", version: RegExp.$1 };
  let os = { name: unknown, version: unknown }; const windows = ua.match(/Windows NT ([\d.]+)/); const android = ua.match(/Android ([\d.]+)/); const ios = ua.match(/(?:iPhone OS|CPU OS) ([\d_]+)/); const mac = ua.match(/Mac OS X ([\d_]+)/); if (windows) os = { name: "Windows", version: windows[1] }; else if (android) os = { name: "Android", version: android[1] }; else if (ios) os = { name: "iOS", version: ios[1].replace(/_/g, ".") }; else if (mac) os = { name: "macOS", version: mac[1].replace(/_/g, ".") }; else if (/Linux/.test(ua)) os = { name: "Linux", version: unknown };
  const engine = /AppleWebKit\/([\d.]+)/.test(ua) ? { name: "WebKit", version: RegExp.$1 } : /Gecko\/([\d.]+)/.test(ua) ? { name: "Gecko", version: RegExp.$1 } : { name: unknown, version: unknown }; const mobile = /Mobile|Android|iPhone|iPad/i.test(ua); const tablet = /iPad|Tablet/i.test(ua); const device = { type: tablet ? "Tablet" : mobile ? "Mobile" : "Desktop", model: /iPhone/.test(ua) ? "iPhone" : /iPad/.test(ua) ? "iPad" : unknown, vendor: /iPhone|iPad/.test(ua) ? "Apple" : /Android/.test(ua) ? "Android device" : unknown }; return { browser, os, engine, device }; }

export type DiffPart = { value: string; added?: boolean; removed?: boolean };
export function diffText(left: string, right: string): DiffPart[] { const a = left.split(/(\s+)/), b = right.split(/(\s+)/); const matrix = Array.from({ length: a.length + 1 }, () => Array<number>(b.length + 1).fill(0)); for (let i = a.length - 1; i >= 0; i--) for (let j = b.length - 1; j >= 0; j--) matrix[i][j] = a[i] === b[j] ? matrix[i + 1][j + 1] + 1 : Math.max(matrix[i + 1][j], matrix[i][j + 1]); const result: DiffPart[] = []; let i = 0; let j = 0; while (i < a.length && j < b.length) { if (a[i] === b[j]) { result.push({ value: a[i] }); i++; j++; } else if (matrix[i + 1][j] >= matrix[i][j + 1]) result.push({ value: a[i++], removed: true }); else result.push({ value: b[j++], added: true }); } while (i < a.length) result.push({ value: a[i++], removed: true }); while (j < b.length) result.push({ value: b[j++], added: true }); return result; }
